apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.docker.internal:6443
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: helm
    repoURL: https://github.com/onlife2007/techtrends
    targetRevision: HEAD
